import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { UserProvider } from "@/context/user-context"
import { GlobalUserGate } from "@/app/global-user-gate"

import { I18nProvider } from "@/i18n/provider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <I18nProvider>
          <UserProvider>
            <GlobalUserGate>{children}</GlobalUserGate>
          </UserProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
